/***
**
**/

package cluster

const (
	RAFT_LEADER     = 1
	RAFT_CANDIDATOR = 2
	RAFT_FOLLOWER   = 3
)

const (
	ROLE_CONTROLLER = "CONTROLLER"
	ROLE_WORKER     = "WORKER"
)

const (
	RPC_VOTE         = "__TOPIIK_VOTE"
	RPC_APPENDENTRY  = "__TOPIIK_APPENDENTRY"
	CLUSTER_JOIN_ACK = "__TOPIIK_CLUSTER_JOIN_ACK"
)

const (
	VOTE_ACCEPTED = "A"
	VOTE_REJECTED = "R"
)

var CLUSTER_CMD_ARRAY = []string{RPC_VOTE, RPC_APPENDENTRY, CLUSTER_JOIN_ACK}
